# Generated by Django 4.2.1 on 2024-08-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='embedding',
            field=models.JSONField(),
        ),
    ]
